### ISSUE TITLE
Clean secrets from git history

### ISSUE THREAD

**Issue by g3kk0** [joinself/restful-client#29]
This project currently exposes secrets in its Git history.

The exposed secrets are no longer valid, but as this is a publicly visible project the secrets should be removed.

**Comment by adriacidre** [comment]
hey @g3kk0 it's been a while since the last updates on this issue, is still relevant or we can close it?

**Comment by g3kk0** [comment]
Closed in favour of https://zube.io/joinself/self/c/12738
